### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by ModEngineer** [DiegoAscanio/python-graphs#1]
This project has LICENSE.md, but it does not contain any text. If possible, could you add something like the MIT License to the project because that way, other people can use your code and not get copyright issues as long as they credit you? I'm looking to use this particular implementation of the Fleury algorithm because of its simplicity.

**Comment by DiegoAscanio** [comment]
Alright my man, I'll.

Im sorry for taking so long to see this.

**Comment by ModEngineer** [comment]
No worries; I learned a lot more about graph theory when writing my own implementation of Fleury's algorithm than I would have if I had just used someone else's code, and funnily enough, the email for this came right as I was working on replacing Fleury's algorithm with Hielholzer's algorithm in my code because Fleury's algorithm isn't performant enough for my use case.

**Comment by ModEngineer** [comment]
Since you just added a license, I might as well close the issue.
